---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-llm-secret
  namespace: bifrost-system
spec:
  encryptedData:
    api-key: AgA7FZrEf33kiS0GQlpDyUhkZovMapuX8YP1lPZYG3nEsH3TXz6EDDTID90ZZwlWcKvK/yxUv7fYtIDik+uMzc0SQSlsp1m0cGs1A7DTmHMsnSuUu/uFctrjybztEClZeclcoF69JXy0ERiQB+u9E28m8ZvmLQR57wlDdvENHfAZeY+IPzUl9keCsUCT0CU7RAbHmbwzW3RkBJUkveaHPdOwYctKVCXk0Ge8+1ReNrsUJMGpYXiDv5UE9MyN6Jr1/0ee79PD6gfa5n9QacDnBAnZx93/m49XCFdoZBPSiBbU0gTV/7pkkugbLUG7OtVkLGgL1svEanHkpBXYAE+4aZjlQZK8kqspzHCtxjHElyZ0EFL3l8VEVRv7yrxTDp/DZQw+dWek+DCGOA2LCotkptrIMt+UyizOuANF1LNsl9G3zMGbQ4L2EOABmjzExaZAi8KRm22BakVXYDpjX69BwJjLcYVJ5s7BybBXYTdu2O91Zo9fzvOCOd4lUUNRt+OQtibBkVllx6On0NLdKCkXvZfhWr5Vgk/fVheWWR9U2YcYa5m2xvkZO/OE1dxSVXE62lRTwn0pTXjTrl8rOjJcg1dIuCu4zvfDt6eZpT/ftZclmvHyjprs8YUDzz7SIsF0b/bBUW3J5tPXUef+KtBII4ZfzuzzfdyyPCdBZzcJsqWefVqPQgAk2shVvHqk5TaZedgivN5AgjDMhsNg3ruQvOhcbRY1BLGUEDECEzM1Lk1dJG9u5WXaBdUKhS1G2XHxTqhWrTF8M1umyAahBuNLiQqQwae4G33L2DXtGpgBX6P7EF72Hb3qnHRUo09IwiMMmM7Blm8rXSn5fQOZZ3KHz2/ptzTtY1cCNUMb+rPty6x+9ggPJnZMzCfyrv2KrqgxpxkNbWdseKxXw/SP08ggGsPNDi8byw==
  template:
    metadata:
      name: ai-llm-secret
      namespace: bifrost-system
    type: Opaque
