---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-llm-secret
  namespace: bifrost-system
spec:
  encryptedData:
    api-key: AgA2okhHRQY3M3aYUlUqw+OLr1hjuSG1E/FwGgr1PyoF3fbzbvdm8z1gYldzVXXtAcP9zY7MZhzp2nmBPdZFgAnuUm4j5FQ1XtFqePH9R6029EVJ1v/tkcVVD+JlfDQzqCoPRQACG6GNRPCdFXNYi/W7hgcWvXBg/kHCdVhe9aSHF0he/Jw1bqfPga1TYoWldz8MHPcLS/I+G2DS3fuQjauA+9XLl26doOIJQ1z5NNYtR8blmfjveOZ2vi1/Ym+KqJUuau8ZkP5+TSxyP39I0q/WL54xC7/gK0eyU5zy/gGmf3JuenK2HLqTunQ5k2LH21LtRdvA3PgMfWZj6J5vHaHyg8LT7EGCgHMSN16xrX8XHlVsLacQG7r5J9LQrqm3rdX1uYF5gYZi5dys+DuI71hzR/e4iTc98FKBI12i0Glm651mAIR4tf0uz7qao1tf2yiPUmWKuyY5EAgOtrlf/efO087qT4/mdBRz7Spadu0YbYkTDMXv0e4U6jIRO0Et7DdLu5xZE8rflDJIh3QE42BwTe9zGsZ1MsWlRPlHeTnMLzjrzaArLLdR/lwqQSHIfOYrSyj2tahptbQyTfVWiL2kclwkRhp1s89Vc+J8EybPsGDfaES51eYR2lkn7CBJ7a2oy69Nu7ysKhpuDjFbPlUgPeuNzU4gkq3i+F5n/2r8buAGp7/RL4ymfg/BuHIjFpt1ElsQGD9kkrTkXdZJs53IWe7Q8zGXrDg9CTmzh2zaTbdVpB428O79iC50PS0Tn4XDaCOQdgvZgo59J7JYAmTkJagUqN5EPd3TjNBngPAyBI0eGEFHpDRIUpAbQbNVtFNHZ0B8OxLxf4rbyarQhOf/0CRghCo/YcJWGLTnBL+yqLob4n3xrm2EYP3fZQuKQYiaaGbDbSRjL2FXAHaNAyP9Gotfmw==
  template:
    metadata:
      name: ai-llm-secret
      namespace: bifrost-system
    type: Opaque
