---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-push-secret
  namespace: bifrost-system
spec:
  encryptedData:
    .dockerconfigjson: AgB6J1MC49+lrkqxcJvZS4ZPQdtYdyOV3L2LokmDZqqQgJDhjnnb5liBub4EGKD2Tc2FjCWT76VwIVzul+rxmqI4lOn5oyimblh0/lkywy+4sorqjGdb/MdGYoihlAW9LCpItU5YPLS/2lMOls10fTNPSVwjkd3Q6n+7dfnzZlLC/Lt/oqrrJN/Ji0NWSsZWQSFvlO91qyn28ZaW9LXGtxARhzRvRIi4FPAW6EWz4KN4Da/2L5mWUZy2a+ISCDmiqm8QsiX2pekOq0wZL2EgcFnrKY7KmSZLkOSk0Uwj6GJmQtlmrODXMalVVDNg5FK5JZFXCnj5R1KhIeiqjQHKCW3THd+vdwLkOhtq+HNn6pxA0AhLGdhz7aci4mA1kj3cFCyZCHPO6MqKeRp3htajbsIkFyKXQTBVwa3UYbFu5xkUaVxujWy0eJVPEbv429ygZE1lPUggXzNmwlX1t3ZWE9VAerW5TlqK0OLDW/w2/bIw4Cdvj+3J/2q5MSi3N4zcFztFsU5jJYcwwEnOYpIPBVp0QtmFT7jq29Rb+jwKTGoLyZNkIkosZhehldhAmgkIvKxkdT1ladGvOHvLEuNxKDTqa/JD9A8H6wj7UubVHGq+dbHzwBXAGDk0MxYzcLH9RB3ukjwJIf61Q4ZEbxGeg/kUoz/qEtl+Zj4alSqGLTPHk3m+LKMWTjauP2Ujjc2iTEdBTf7FCDSYmPsX0/Edts5X9sz9l50b+rzWTjRRt+Qc6x4FJPwUr1Qskk1882i5RoolE7VNJVEb3cK4ykMikvLCuFw22h+tVjL+EEvxHY1ystZpoytdxC3aRTI/9Rw5GapWXAZTl7O2e0keDCVTQUeNSsVzKkSc5uQsjBynwRLV67rL8OZJYdcFq8fSob19lpCWUOQhefnEIEKeANXoG8mwygumCU5Jm5wcXgqQrV0Jf6tWfQf5Q3XB6MCA1QBTblrgMFJNheCLCdSDbH1PgmZpA6TJjkmJSk3FXYtT0aS9gQ==
  template:
    metadata:
      name: harbor-push-secret
      namespace: bifrost-system
    type: kubernetes.io/dockerconfigjson
