---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operations-backend-secrets
  namespace: bifrost-system
spec:
  encryptedData:
    JWT_SECRET: AgAXrYgz/lXFOXJzCJM1yrhUtlh8c2cqm+aIpqYlSLV1qAaEABzSodPBe1osM/Nlz/Vjf8wyV8ROxwRHe2WadCOifxHcEgpkq9rriF2PYTtcheDPexMu0XeTvBPsPIta0wGjQ9l4HbXU39PIRUj9LEMsNxzz3zaOFDUKwlnuY4Exgb0UA8xCQ+/49BkLbjbCFW/CnsvoenbceEW0C6/wpUbQjbGHzpVngSJs2imjd1k+d4iDIHI0nP0qBJ6dMhLGVexP06xJdD2yiJ6doAjeGd+KJJGI15n6pfx3ycI4/RsI3RreEgyJVGNsu/JFQp+4iIxZIyy/ESd/9/746pnFX82HgVx4qBr2fViagk7ctlsvEX4E6k0EBIWBNXKbr2X2LDHs2SH/kKL0TSa/4z91SxGkVamG1lSlf0VuTimksKdr1UgW8fc3QeWNxn31FgQ7YxYYdxrnNnkVhq8Br47VKOf5GbbVaWxfNDg5n2pjuRZUQ2v3WBjvk5lpZkzJepVHD92VLxWe22Gu6AIEyxg44cfijbtMbhSZzXdhy0LgaLsOnJB2T5v8xVypkqS2Xvsbj1pDWdq7U54audGeiUIrMRshz5aMQueKX7WO4b3+m37Tio+eqcOujiklCz9jw8KVGHP/zhoH62exGISLX3ioyqDhvcEUcNfC7rgjGT7ilerGY5hJ9/28BWceyQTMRdo6c18IHBmI17YGQege+niXaWKPgGncIyBX1BaPN/uYtCR4kqsw5g1Q18s1O1/M2B9RJsq/KSNdpF0gEQbYy4sQ1PWp
    META_DB_PASSWORD: AgCcNNjGcxsF6RYw4u2s1O966zGSBz6lGKgL5NO4j4JlrtUYmNvbjz+sYZzsUFBrBOyVXSdKc+F/2nk5ifQq4U6OY7SIhgcqiSyCE4AabfeJgRQlQy7L2KCgWzWvvszTKeML87ENIq5EKGkYcWPmZfneoxvVA4QgSQif2dPvaqszIFKzIw8y6v6B4ck0eWVSIslh/1YPUVE0A9AFeJCGYb1I9yeQhyt+pMVLr1DQ3PczI/SZsrdNoix7B+tzUgYCXcU+H7HuGoh8qvtUkerS+eLmoVRqYcBnfy6F1evuIVWdjOdQ9fPCCSfNgVZAX8giwmqa8A3GsEFYVQzHCBlAilPZVcYDnmqzm46FUUFUAbnidbdv1tCYKRnhNqKuiffFK1k7brwHo4vnbNc1k2ZE4Le9+D3Z549UZIvPia87QxATBWeH6uI+eBhfItHBqJdLzWqrs8xqXrSVFGR9+63bP+kUsxKOm1/uVyyVB/MkuceFIml9LuZ5hvuqVKpxTOeSRHWIftqRAz7kemxuMUOvIWJuC740wP3PUZjCH1MyYtvn9vQbyiUSh2c5AxS9/XGd7FmLlE0z1BLepMJU4uQLv6utImIyvwnx1JoTU3xUBWgPMi01dJ7aUryriKfejyaXPngc5/VznZwtLuHtvrw7K09AUFNDXwYaVyDdJyOqENDYltfaOT96bPr8KKyOZG8DyFAsP8DC2w4GSSwZ5m8R5xKLLkl3QZumgQ==
  template:
    metadata:
      name: operations-backend-secrets
      namespace: bifrost-system
    type: Opaque
