# Debezium MariaDB CDC 필수 설정
# binlog_format=ROW + binlog_row_image=FULL: 변경된 row 전체를 로그에 기록 (CDC 필수)
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-mariadb-config
  namespace: userdb
data:
  my.cnf: |
    [mysqld]
    server-id            = 1
    log-bin              = binlog
    binlog-format        = ROW
    binlog-row-image     = FULL
    expire-logs-days     = 1
    gtid-strict-mode     = ON
    log-slave-updates    = ON
