apiVersion: v1
kind: ConfigMap
metadata:
  name: operations-backend-env
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
