apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1-platform-cicd-ingress
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/cloud-team2/bifrost.git
    targetRevision: gitops
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: default      # ingress 템플릿이 자체 namespace 지정
  syncPolicy:
    automated: { prune: false, selfHeal: true }
