apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operations-backend
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/cloud-team2/bifrost.git
    targetRevision: gitops
    path: charts/operations-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: bifrost-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
