{{- if .Values.jenkins.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: {{ .Values.jenkins.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.jenkins.host }}
      secretName: jenkins-tls
  rules:
    - host: {{ .Values.jenkins.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: {{ .Values.jenkins.servicePort }}
{{- end }}
